package com.learningandroid.lukas.signos;

import android.support.v7.app.AppCompatActivity;
import android.os.Bundle;
import android.view.View;
import android.widget.Adapter;
import android.widget.AdapterView;
import android.widget.ArrayAdapter;
import android.widget.ListView;
import android.widget.Toast;

public class MainActivity extends AppCompatActivity {

    private ListView listaSignos;
    private String[] signos = {
        "Áries","Touro","Gêmeos","Câncer","Leão","Virgem","Libra","Escorpião","Sagitário","Capricórnio","Aquário","Peixes"
    };

    private String[] perfis = {
            "Signo de fogo, regido por Marte, que confere, entre outras coisas, a vontade de expandir-se, conquistar, e o impulso de lutar. Os arianos em geral possuem grande energia e vitalidade. São corajoso, combativos, e costumam ter as qualidades necessárias para vencer, realizar, comandar, impor disciplina. São fisicamente harmoniosos e sexualmente atraentes. Ainda que não demonstrem, podem ser temperamentais, agressivos e muito impacientes. Seu espírito aventureiro e de liderança exige muito autocontrole e energia vital, o que, às vezes, pode provocar um desgaste. Gostam de enfrentar desafios, com sua imensa coragem, que adoram exibir constantemente, e que é muito admirada. São impulsivos e ardentes por natureza. São muito individualistas, mas não gostam de viver sozinhos. São animados independentes, dinâmicos, e gostam de liderar. Interessam-se por atividades competitivas, exercícios, música rítmica, entre outras coisas.",
            "Signo de terra, regido por Vênus, que confere sensibilidade, estabilidade e profundidade às emoções, e disposições amáveis. As pessoas de Touro são, em geral, amantes de beleza, do conforto, de tudo o que der prazer, e do romantismo, em especial. São muito esforçados, e sua teimosia faz com que cheguem às últimas conseqüências em seus empreendimentos. Sua paciência e determinação acabam sendo de grande ajuda nos negócios. São práticos, econômicos, e seu objetivo é adquirir patrimônio. Gostam de conforto e luxo. Normalmente, programas culturais de boa qualidade e projetos urbanos bem elaborados costumam atraí-los. Possuem sempre muito gosto pela vida, e procuram tanto o bem estar material quanto o espiritual. Interessam-se por música clássica ou romântica. São conservadores, pacientes, leais e dignos de confiança. Podem ser também teimosos, auto-indulgentes, possessivos, gulosos e materialistas.",
            "Signo de Ar, regido por Mercúrio, que confere inteligência, versatilidade, agilidade mental, sociabilidade, grande poder de persuasão. As pessoas de Gêmeos são naturalmente inquietas e curiosas, sempre muito comunicativas.Preocupam-se muito com atividades intelectuais, e procuram amigos igualmente inteligentes. Adaptam-se facilmente a qualquer tipo de ambiente ou pessoa. Isso faz com que possam viver várias experiências ao mesmo tempo, tirando de todas grande proveito. Uma das principais características de Gêmeos é a jovialidade, o que faz com que raramente amadureçam, embora sejam capazes de compreender perfeitamente a complexidade das situações. Curiosas por natureza, as pessoas desse signo gostam de experimentar e conhecer de tudo um pouco. O tédio é o seu maior inimigo, e a falta de atividades costuma aborrecê-los. São alegres, entusiasmados, comunicativos, eloqüentes, têm facilidade para aprender e ensinar. Interessam-se por eventos de vários tipos - músicas, em geral -, atividades em educação, comércio, comunicação. Às vezes podem ser indiscretos e instáveis.",
            "Signo de água regido pela Lua, o que confere enormes sensibilidade e criatividade, e inclina á vida doméstica. São por natureza indivíduos muito simpáticos e bem humorados, mas ao mesmo tempo introvertidos, tímidos e sonhadores; parecem estar sempre nas nuvens. Por serem muito reservados, é sempre difícil ajudá-los. Retiram-se para dentro de sua casca, prudentemente, toda vez que sente negatividade ou desarmonia pairando no ar. São muito criativos, bastante emotivos e muito protetores. Estão constantemente ajudando os outros e envolvendo-se numa boa causa, o que satisfaz seu enorme desejo de ser útil. Apreciam todo tipo de música, conforme seu estado de espírito. Sentem-se atraídos por problemas sociais, trabalho voluntário e qualquer atividade em prol dos menos favorecidos. São intuitivos, maternais, muito inteligentes, dotados de ótima memória, prudentes, afetivos, dedicados e idealistas. Mas podem também ser crédulos, impacientes, irritadiços, obstinados manipuladores, e egoístas. Sempre muito apegados aos assuntos familiares e domésticos, 'seu lar é seu castelo'. Precisam da segurança do lar e da família, mesmo que não seja durante todo o tempo. Muito leais às amizades, costumam dar muita importância, especialmente, aos 'velhos amigos'', aos quais costumam ser muito apegados. Não é raro escolherem atividades profissionais que possam ser desenvolvidas dentro de casa. Muito sensíveis, podem magoar-se com facilidade, e seu estado de espírito pode oscilar.",
            "Signo de fogo regido pelo Sol, que torna os nativos saudáveis, bonitos, carismáticos, cheios de vida, exuberantes e comunicativos. Os leoninos caminham decididamente em direção ao sucesso, e só se contentam com a glória. Podem ser ambiciosos e vaidosos, sempre conscientes dos seus méritos, e quase nunca de seus limites. Seu espírito é de líder, ou, é aquele que sempre ocupa o centro do palco. Podem superar-se, e seus objetivos são elevados. Estão sempre envolvidos em projetos de grande vulto, artísticos ou para exibição pública, que quase sempre são reconhecidos com elogios ou prêmios. Suas atitudes, geralmente, tendem a ser dramáticas. São dignos, leais e estáveis, extrovertidos e muito generosos. São ingênuos, às vezes. Gostam de músicas de cinema, baladas, baladas, grandes concertos, óperas e canções românticas. Idealistas, criativos, orgulhosos, sabem perceber o lado bom das pessoas e costumam ser excelentes amigos. Podem também ser arrogantes, vaidosos, cruéis e pretensiosos.",
            "Signo de terra regido por Mercúrio, que confere raciocínio lógico, inteligência, bastante sensibilidade, agilidade mental, capacidade de análise e poder de observação. Os virginianos são bastante reservados, mas muito afetuosos, demonstrando seus sentimentos com atitudes delicadas e pouco comuns. São críticos e introspectivos, perfeccionistas, atentos à detalhes. Esse perfil costuma criar dificuldades em fazer amizades, pois torna-os muito seletivos. Entretanto, sentem-se à vontade em ambientes culturais ou com amigos intelectuais. Apresentam uma imagem convencional. Adaptem-se bem a qualquer trabalho que exija atenção à detalhes. São práticos, e saem-se bem no trato com o público, no comércio, artes, educação, entre outras coisas. Gostam de armazenar conhecimento, e se interessam por análise e pesquisa. Quando em desarmonia, podem ser submissos, nervosos, pedantes, materialistas, solitários. Gostam de música, do clássico ao new age, artesanato, antiguidades, qualquer atividade prática.",
            "Signo de ar regido por Vênus, que exalta a sensibilidade e refina as emoções e sensações. Está associado à beleza, ao amor e à harmonia. As pessoas de Libra são românticas, e sempre dispostas ao amor. Gostam de participar da vida social, de preferência acompanhadas de gente interessante. São amáveis e simpáticas, muito alegres, elegantes, compreensivas e generosas. Gostam de luxo e conforto, das coisas requintadas, arte, beleza e cultura. Os librianos não são adeptos do esforço físico, mas apreciam todo trabalho que dependa da inteligência, habilidade e bom gosto. Envolvem-se com atividades artísticas, com moda, e em tudo que exija apurado senso estético. Gostam de seduzir. São inclinados ao casamento e à vida em família, mas também adoram divertimentos, bem como a companhia de amigos e pessoas cultas. Podem ser inconstantes, intrigantes, desanimar facilmente, orgulhosos, apáticos.",
            "Signo de Água regido por Plutão, que confere grande magnetismo e poder, determinação e criatividade. Os nascidos em Escorpião são inteligentes, arredios, têm emoções e sentimentos fortes, são muito persistentes, mas também podem ser rancorosos e obstinados. Desconfiados e ciumentos, resguardam a sua privacidade a todo custo, e preservam a vida familiar da maneira mais tradicional possível. Sentem-se atraídos pela competição, e para isso contam com uma enorme inteligência, além de serem bons estrategistas. O sangue frio é sua melhor arma. Despertam a curiosidade das pessoas, graças ao mistério que criam em torno de si. São muito exigentes em tudo. Costumam ser bastante discretos, especialmente na vida profissional. Podem tornar-se materialistas e consumistas crônicos. Em certas ocasiões, podem ser vingativos, sarcásticos, intolerantes, manipuladores, cruéis e vaidosos. São impacientes.",
            "Signo de fogo regido por Júpiter, que confere generosidade, nobreza, sinceridade e dignidade, bem como uma natureza otimista e jovial, e um caráter justo. Os sagitarianos são inteligentes, de raciocínio brilhante, profundo e lógico. Ensinam e aprendem com igual facilidade. São sempre detalhistas, exigentes, impulsivos. Exuberantes e entusiasmados, podem tender ao exagero, às vezes. Interessam-se por turismo, viagens, aventuras, assuntos comunitários, política, religião, comércio, esportes, e adoram desafios. Às vezes são inconstantes, e costumam se interessar por vários assuntos ou atividades, sem se aprofundar em nenhum. Espaço e movimento são essenciais para seu equilíbrio físico e mental, e precisam sempre conservar a sua independência. Muito intuitivos e diplomáticos, são ótimos para lidar com situações de risco. Em alguns casos, podem se tornar prepotentes, esbanjadores, imprudentes, rebeldes,inconstantes e tagarelas. Atuam melhor em profissões liberais. Apreciam música e artes.",
            "Signo de terra, regido por Saturno, que confere solidez, ambição e cautela. Os capricornianos fazem planos, e têm paciência de deixa-los amadurecer. São modestos, reservados, tranqüilos, práticos e econômicos. São persistentes, e não desistem enquanto não conquistam seus objetivos. Não são amantes de vida social intensa, nem muito comunicativos, entretanto possuem habilidade para comércio e finanças. Corajosos e objetivos, enfrentam situações difíceis com diplomacia. Podem ser desconfiados, principalmente no campo afetivo, porém, são muito fiéis e protetores, e inspiram confiança. Essa característica pode torna-los um pouco solitários. Colocam a vida afetiva em segundo plano, dando especial atenção aos interesses profissionais, ou à coisas que reafirmem seu prestígio. Às vezes, não se importam de passar por cima das pessoas nessa busca profissional e social. Gostam de música séria, bem elaborada, clássicos, antiguidades. Prefere a vida tranqüila e modesta.",
            "Signo de ar regido por Urano, que confere dons artísticos, capacidade critica, genialidade, originalidade, intuição acentuada. Aquário é um signo fraterno, e os aquarianos costumam ser dotados de forte espírito humanitário. São progressistas e muito avançados em suas idéias, o que faz com que sejam considerados, quase sempre, muito adiantados para seu tempo. Para os aquarianos, a vida tem que ter colorido e circunstâncias inusitadas. Independentes, não gostam de estar presos a compromissos, ou sentirem-se amarrados. Entretanto, apreciam a companhia das pessoas, as quais, geralmente, sentem-se atraídas por sua personalidade agradável e cativante. Dotados de agilidade mental invejável e de grande senso de oportunidade, às vezes, podem dar a impressão de desleais e oportunistas. Adoram fazer amigos, e não toleram qualquer tipo de segregação ou preconceito. São pacientes, perseverantes, humanitários, teimosos e muito independestes. Procuram sempre agir de maneira pacífica. A rebeldia e a originalidade podem ser consideradas como sua marca registrada. Gostam de lidar com métodos e idéias modernas, fora do comum e, se possível, em benefício da humanidade.",
             "Signo de água, regido por Netuno. Sonhadores, emotivos, muito receptivos, indecisos, sensuais, os piscianos podem ser considerados os mais maleáveis em todo o zodíaco, com todas as características, positivas ou negativas, que esta particularidade possa conferir. Possuem personalidade sensível e impressionável, podendo chegar à instabilidade emocional. São facilmente afetados por pessoas ou ambientes. Por esse motivo, têm facilidade para sentir o problema dos outros, 'como se fosse seu'.e 'as vezes, tendem a anular-se ou submeter-se a uma vontade mais firme que a sua. Por outro lado, são muito inspirados, intuitivos e humanitários, sempre dando mostras de um profundo amor às pessoas. Sua personalidade é bastante complexa, e ao mesmo tempo em que se abre para a vida, se fecha em seu mundo, evitando encarar a dura realidade cotidiana. A generosidade e a justiça são suas grande marca. Ligam-se com freqüência a atividades místicas ou religiosas, interessam-se por cinema, música, artes em geral e, não raro, exercem atividades em instituições filantrópicas."
    };

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);

        listaSignos = (ListView) findViewById(R.id.listviewid);

        ArrayAdapter<String> adapter = new ArrayAdapter<String>(
                getApplicationContext(),
                android.R.layout.simple_list_item_1,
                android.R.id.text1,
                signos
        );

        listaSignos.setAdapter( adapter );

        listaSignos.setOnItemClickListener(new AdapterView.OnItemClickListener() {
            @Override
            public void onItemClick(AdapterView<?> parent, View view, int position, long id) {
                Toast.makeText(MainActivity.this, perfis[position], Toast.LENGTH_SHORT).show();
            }
        });
    }
}
